# Generated by Django 3.0.7 on 2020-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('coach_id', models.UUIDField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('appointment_id', models.UUIDField(blank=True, null=True)),
                ('service_id', models.UUIDField(blank=True, null=True)),
                ('available_slots', models.IntegerField(blank=True, null=True)),
                ('commercial', models.BooleanField(default=False)),
                ('client_recorded', models.BooleanField(default=False)),
                ('tab', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
